### ISSUE TITLE
Allure Cucumber-jvm cannot generate html result, only json

### ISSUE THREAD

**Issue by brobee** [allure-framework/allure1#974]
Hi,

I tried to generate html test result, but I got only json. html generation info can be found in the documentation but only for gradle, js etc. not for cucumber-jvm. I created my pom.xml according to the cucumber-jvm. allure-results folder and json is generated, but no option for html.

Any idea? Thank you!

**Comment by symonk** [comment]
Hi @brobee, I am not entirely familiar with allure1 (I assume you are using it because this issue is under allure1) but there is a 2 part phase involved.  If you are using cucumber jvm I would highly recommend moving to allure2.

Typically you run your tests which will output to an allure-results directory, usually by default in /target.  Next you then run allure-maven/allure from command line yourself / allure jenkins **generator** which will take your allure-results directory and create an allure report directory with the visual frontend there, jenkins can attach this to the pipeline artifacts etc.

Please post some more info and I will try to aid you more, I am not completely sure from your post and am not very familiar with allure1 at all

**Comment by baev** [comment]
> allure-results folder and json is generated, but no option for html.

if allure-results folder contains json files that means you need to use allure 2 anyway. So install latest allure commandline and generate the report

https://docs.qameta.io/allure/#_reporting

**Comment by baev** [comment]
https://github.com/allure-framework/allure-maven
https://github.com/allure-framework/allure-teamcity
