### ISSUE TITLE
https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip is forbidden. Please fix this ASAP.

### ISSUE THREAD

**Issue by sjana-aurea** [allure-framework/allure1#980]
https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip is forbidden. This is breaking our CI Allure integration. Can you please help to fix the issue?

**Comment by baev** [comment]
our bintray account has been rate-limited due to overuse. JFrog support team are working on the issue.

At the moment you can configure your CI to download Allure from Github releases page

https://github.com/allure-framework/allure2/releases

Direct link to download latest release https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.zip

The issue to track status https://github.com/allure-framework/allure2/issues/832
